language: clojure
lein: lein2
before_install:
  - sudo apt-get -qq update > /dev/null
  - sudo apt-get -qq install graphviz > /dev/null
script: lein2 with-profile dev midje && lein2 uberjar
jdk:
  - openjdk6
  - openjdk7
  - oraclejdk7
  - oraclejdk8
sudo: false
